# RCade Cabinet Package
#
# Builds the RCade cabinet Electron app reproducibly using bun2nix.
# Dependencies are locked via bun.nix (generated by `bun2nix`).
#
# To update dependencies:
#   1. Run `bun install` to update bun.lock
#   2. Run `bun2nix` to regenerate bun.nix
#   3. Rebuild with `nix build .#cabinet`
#
# Build architecture:
#   bun build (main.ts)    → dist/main/main.js     (ESM, --external electron)
#   bun build (preload.ts) → dist/main/preload.js   (CJS, --external electron)
#   vite build             → dist/renderer/          (Svelte SPA)
#
# All workspace deps (@rcade/*) and npm deps (hono, tar, semver, etc.) are
# bundled into the output files by bun. Only `electron` and node builtins
# remain as external imports at runtime.
#
# node-hid (native addon for arcade spinner hardware) is loaded at runtime
# via the bundled input-spinners plugin. It needs node_modules available.

{ lib
, stdenv
, makeWrapper
, electron
, bun
, nodejs_22
, bun2nix

# Runtime dependencies for Electron on Linux
, alsa-lib
, at-spi2-atk
, at-spi2-core
, atk
, cairo
, cups
, dbus
, expat
, gdk-pixbuf
, glib
, gtk3
, libdrm
, libxkbcommon
, mesa
, nspr
, nss
, pango
, systemd
, vulkan-loader
, xorg
, libGL
, pipewire
, libpulseaudio
}:

let
  pname = "rcade-cabinet";
  version = "0.2.1";

  runtimeLibs = [
    alsa-lib
    at-spi2-atk
    at-spi2-core
    atk
    cairo
    cups
    dbus
    expat
    gdk-pixbuf
    glib
    gtk3
    libdrm
    libxkbcommon
    libGL
    mesa
    nspr
    nss
    pango
    pipewire
    libpulseaudio
    systemd
    vulkan-loader
    xorg.libX11
    xorg.libXcomposite
    xorg.libXdamage
    xorg.libXext
    xorg.libXfixes
    xorg.libXrandr
    xorg.libxcb
    xorg.libxshmfence
  ];

  # Only include what the cabinet build actually needs as source.
  # The full repo is required because bun2nix resolves workspace packages
  # (via copyPathToStore in bun.nix) relative to the repo root.
  src = lib.cleanSourceWith {
    src = ../..;
    filter = path: type:
      let
        baseName = baseNameOf path;
      in
      !(
        baseName == "node_modules" ||
        baseName == ".git" ||
        baseName == "dist" ||
        baseName == "release" ||
        baseName == ".turbo" ||
        baseName == ".svelte-kit" ||
        baseName == ".vite" ||
        baseName == ".claude" ||
        lib.hasPrefix "result" baseName ||
        lib.hasSuffix ".log" baseName
      );
  };

  bunDeps = bun2nix.fetchBunDeps {
    bunNix = ../../bun.nix;
  };

in
stdenv.mkDerivation {
  inherit pname version src;

  nativeBuildInputs = [
    makeWrapper
    bun
    nodejs_22
    bun2nix.hook
  ];

  inherit bunDeps;

  # bun2nix hook sets up node_modules from bunDeps automatically.
  # We skip the hook's default build phase since we have custom build steps.
  dontUseBunBuild = true;

  buildPhase = ''
    runHook preBuild

    export HOME=$(mktemp -d)

    cd cabinet

    # Main process: bundles all workspace + npm deps, externalizes electron
    ${bun}/bin/bun build src/main/main.ts \
      --outdir dist/main \
      --target node \
      --external electron

    # Preload script: must be CJS (electron requirement)
    ${bun}/bin/bun build src/main/preload.ts \
      --outdir dist/main \
      --target node \
      --format cjs \
      --external electron

    # Renderer: Svelte SPA via vite
    # node_modules is at the repo root (bun workspace hoisting), not in cabinet/
    ../node_modules/.bin/vite build

    cd ..

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/lib/rcade-cabinet $out/bin

    # Built artifacts
    cp -r cabinet/dist $out/lib/rcade-cabinet/

    # package.json is required — electron uses "main" field to find the entry point
    cp cabinet/package.json $out/lib/rcade-cabinet/

    # Assets: icons, fonts (NotoColorEmoji.ttf), audio files
    cp -r cabinet/assets $out/lib/rcade-cabinet/

    # node-hid native addon: the input-spinners plugin loads this at runtime
    # via require("node-hid"). bun can't bundle native .node addons, so we
    # need the node_modules tree available for this one dependency.
    if [ -d node_modules/node-hid ]; then
      mkdir -p $out/lib/rcade-cabinet/node_modules
      cp -r node_modules/node-hid $out/lib/rcade-cabinet/node_modules/
    fi

    # Launcher script
    cat > $out/bin/rcade-cabinet <<'LAUNCHER'
#!/usr/bin/env bash
set -euo pipefail
APP_DIR="$(dirname "$(dirname "$(readlink -f "$0")")")/lib/rcade-cabinet"
exec electron "$APP_DIR" "$@"
LAUNCHER
    chmod +x $out/bin/rcade-cabinet

    wrapProgram $out/bin/rcade-cabinet \
      --prefix PATH : "${lib.makeBinPath [ electron ]}" \
      --prefix LD_LIBRARY_PATH : "${lib.makeLibraryPath runtimeLibs}" \
      --set ELECTRON_DISABLE_SECURITY_WARNINGS "true"

    runHook postInstall
  '';

  meta = with lib; {
    description = "RCade arcade cabinet Electron application";
    homepage = "https://github.com/recursecenter/rcade";
    license = licenses.mit;
    platforms = platforms.linux;
    mainProgram = "rcade-cabinet";
  };
}
