# RCade Cabinet Package
#
# Builds the RCade cabinet Electron app reproducibly using bun2nix.
# Dependencies are locked via bun.nix (generated by `bun2nix`).
#
# To update dependencies:
#   1. Run `bun install` to update bun.lock
#   2. Run `bun2nix` to regenerate bun.nix
#   3. Rebuild with `nix build .#cabinet`
#
# Build architecture:
#   bun build (main.ts)    -> dist/main/main.cjs     (CJS, --external electron)
#   bun build (preload.ts) -> dist/main/preload.js    (CJS, --external electron)
#   vite build             -> dist/renderer/           (Svelte SPA)
#
# All workspace deps (@rcade/*) and npm deps (hono, tar, semver, etc.) are
# bundled into the output files by bun build. Only `electron` and node builtins
# remain as external imports at runtime.
#
# node-hid (native addon for arcade spinner hardware) is loaded at runtime
# via the bundled input-spinners plugin. It needs node_modules available.

{ lib
, stdenv
, makeWrapper
, autoPatchelfHook
, electron
, bun
, nodejs_22
, bun2nix

# Runtime dependencies for Electron on Linux
, alsa-lib
, at-spi2-atk
, at-spi2-core
, atk
, cairo
, cups
, dbus
, expat
, gdk-pixbuf
, glib
, gtk3
, hidapi
, libdrm
, libusb1
, libxkbcommon
, mesa
, nspr
, nss
, pango
, systemd
, vulkan-loader
, xorg
, libGL
, pipewire
, libpulseaudio
}:

let
  pname = "rcade-cabinet";
  version = "0.2.1";

  # bun2nix v2 API: use passthru attributes on the package
  bun2nixPkg = bun2nix.packages.${stdenv.hostPlatform.system}.default;

  runtimeLibs = [
    alsa-lib
    at-spi2-atk
    at-spi2-core
    atk
    cairo
    cups
    dbus
    expat
    gdk-pixbuf
    glib
    gtk3
    hidapi
    libdrm
    libxkbcommon
    libGL
    mesa
    nspr
    nss
    pango
    pipewire
    libpulseaudio
    systemd
    vulkan-loader
    xorg.libX11
    xorg.libXcomposite
    xorg.libXdamage
    xorg.libXext
    xorg.libXfixes
    xorg.libXrandr
    xorg.libxcb
    xorg.libxshmfence
  ];

  # Only include what the cabinet build actually needs as source.
  src = lib.cleanSourceWith {
    src = ../..;
    filter = path: type:
      let
        baseName = baseNameOf path;
      in
      !(
        baseName == "node_modules" ||
        baseName == ".git" ||
        baseName == "dist" ||
        baseName == "release" ||
        baseName == ".turbo" ||
        baseName == ".svelte-kit" ||
        baseName == ".vite" ||
        baseName == ".claude" ||
        lib.hasPrefix "result" baseName ||
        lib.hasSuffix ".log" baseName ||
        lib.hasInfix "cli/templates" path
      );
  };

in
stdenv.mkDerivation {
  inherit pname version src;

  nativeBuildInputs = [
    makeWrapper
    autoPatchelfHook
    bun
    nodejs_22
    bun2nixPkg.hook
  ];

  # Libraries needed by the node-hid native addon (.node prebuild).
  # autoPatchelfHook patches the RPATH of ELF binaries in $out to point here.
  buildInputs = [
    hidapi
    libusb1
    systemd       # libudev
    stdenv.cc.cc  # libstdc++
  ];

  bunDeps = bun2nixPkg.fetchBunDeps {
    bunNix = ../../bun.nix;
  };

  # Skip bun2nix's default build and check phases - we handle them ourselves
  dontUseBunBuild = true;
  dontUseBunCheck = true;

  # Workaround for bun2nix issues #73 and #77:
  # - #73: Cache copied from nix store is read-only; bun needs write access
  # - #77: bun2nix only creates flat cache entries (pkg@ver@@@1) but bun also
  #   expects hierarchical entries (pkg/ver@@@1) to resolve packages
  postBunSetInstallCacheDirPhase = ''
    chmod -R u+rwx "$BUN_INSTALL_CACHE_DIR"

    find "$BUN_INSTALL_CACHE_DIR" -maxdepth 2 -name '*@@@1' | while read -r flat_entry; do
      rel_path="''${flat_entry#$BUN_INSTALL_CACHE_DIR/}"
      pkg="" ver=""
      if [[ "$rel_path" =~ ^(@[^@/]+/[^@]+)@([0-9].*)$ ]]; then
        pkg="''${BASH_REMATCH[1]}"
        ver="''${BASH_REMATCH[2]}"
      elif [[ "$rel_path" =~ ^([^@]+)@([0-9].*)$ ]]; then
        pkg="''${BASH_REMATCH[1]}"
        ver="''${BASH_REMATCH[2]}"
      fi
      if [ -n "$pkg" ] && [ -n "$ver" ]; then
        mkdir -p "$BUN_INSTALL_CACHE_DIR/$pkg"
        if [ ! -e "$BUN_INSTALL_CACHE_DIR/$pkg/$ver" ]; then
          ln -s "$flat_entry" "$BUN_INSTALL_CACHE_DIR/$pkg/$ver"
        fi
      fi
    done
  '';

  buildPhase = ''
    runHook preBuild

    export HOME=$(mktemp -d)

    # Build workspace dependencies via turbo
    node_modules/.bin/turbo build --filter="@rcade/api" --filter="@rcade/input-classic" --filter="@rcade/input-spinners" --filter="@rcade/sleep" --filter="@rcade/plugin-sleep" --filter="@rcade/plugin-menu-backend" --filter="@rcade/sdk" --filter="@rcade/sdk-plugin"

    cd cabinet

    # Build main process (CJS for Electron with "type": "module")
    bun build src/main/main.ts --outfile dist/main/main.cjs --target node --format cjs --external electron --external node-hid

    # Build preload script (CJS required by Electron)
    bun build src/main/preload.ts --outdir dist/main --target node --format cjs --external electron

    # Build renderer (Svelte SPA via vite)
    node_modules/.bin/vite build

    cd ..

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/lib/rcade-cabinet $out/bin

    # Built artifacts
    cp -r cabinet/dist $out/lib/rcade-cabinet/

    # package.json is required - electron uses "main" field to find the entry point
    cp cabinet/package.json $out/lib/rcade-cabinet/package.json

    # Assets: icons, fonts (NotoColorEmoji.ttf), audio files
    cp -r cabinet/assets $out/lib/rcade-cabinet/

    # node-hid native addon: the input-spinners plugin loads this at runtime
    # via require("node-hid"). bun build can't bundle native .node addons, so we
    # need the node_modules tree available for this one dependency.
    # pkg-prebuilds is also required (node-hid uses it to locate .node binaries).
    if [ -d node_modules/node-hid ]; then
      mkdir -p $out/lib/rcade-cabinet/node_modules
      cp -rL node_modules/node-hid $out/lib/rcade-cabinet/node_modules/
      cp -rL node_modules/pkg-prebuilds $out/lib/rcade-cabinet/node_modules/

      # Remove prebuilds for other platforms/architectures. autoPatchelfHook
      # would fail on musl and non-linux binaries it can't patch.
      find $out/lib/rcade-cabinet/node_modules/node-hid/prebuilds \
        -mindepth 1 -maxdepth 1 -type d \
        ! -name 'HID_hidraw-linux-x64' \
        ! -name 'HID-linux-x64' \
        -exec rm -rf {} +
    fi

    # Launcher script
    cat > $out/bin/rcade-cabinet <<'LAUNCHER'
#!/usr/bin/env bash
set -euo pipefail
APP_DIR="$(dirname "$(dirname "$(readlink -f "$0")")")/lib/rcade-cabinet"
exec electron "$APP_DIR" "$@"
LAUNCHER
    chmod +x $out/bin/rcade-cabinet

    wrapProgram $out/bin/rcade-cabinet \
      --prefix PATH : "${lib.makeBinPath [ electron ]}" \
      --prefix LD_LIBRARY_PATH : "${lib.makeLibraryPath runtimeLibs}" \
      --set ELECTRON_DISABLE_SECURITY_WARNINGS "true" \
      --set ELECTRON_FORCE_IS_PACKAGED "1" \
      --set RCADE_NIX "true"

    runHook postInstall
  '';

  meta = with lib; {
    description = "RCade arcade cabinet Electron application";
    homepage = "https://github.com/recursecenter/rcade";
    license = licenses.mit;
    platforms = platforms.linux;
    mainProgram = "rcade-cabinet";
  };
}
